### ISSUE TITLE
See about integrating PostgreSQL persistent DB into template

### ISSUE THREAD

**Issue by InfoSec812** [InfoSec812/openshift-sonarqube#6]
If possible, configure the template such that proper dependency management is done (do not attempt to deploy sonar server until PostgreSQL service is available).

**Comment by InfoSec812** [comment]
Resolved by PR #7

**Comment by sherl0cks** [comment]
@InfoSec812 @mdanter I'd like to understand why this issue is closed. I still see postgreSQL in the template?

**Comment by sherl0cks** [comment]
closing as this be handled with https://github.com/rht-labs/labs-ci-cd/issues/19
